# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(169, 185, 255);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 70, 151, 51))
        self.pushButton.setStyleSheet("background-color: rgb(162, 170, 146);\n"
"font: 8pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 160, 151, 51))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Nirmala UI Semilight\";\n"
"background-color: rgb(162, 170, 146);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 50, 47, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("F:/projet d\'été/projet/Webp.net-resizeimage.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 170, 51, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("F:/projet d\'été/projet/Webp.net-resizeimage (1).png"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TSP using ACO"))
        self.pushButton.setText(_translate("Dialog", "Chercher le chemin"))
        self.pushButton_2.setText(_translate("Dialog", "Modifier les coordonnées"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
